name: Greetings

on:
    push:
      branches: [ main ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:

      - name: Check if user is part of sre team
        id: checkUserMember
        run: echo Success

      - name: Reply to issue or pull request
        if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
        run: echo "Hello, Thank you for your PR!"
