name: Greetings

on:
    push:
      branches: [ main ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:

      - name: Check if user is part of sre team
        id: checkUserMember
        run: exit 1 #echo Success

      - name: Reply to issue or pull request
        if: ${{ always() && steps.checkUserMember.outcome == 'failure' }}
        run: echo "Hello, Thank you for your PR!"
